language: python
python:
 - "2.7"
#command to install deps:
install: "pip install -r requirements.txt"
#command to run tests:
script: 
 - python -m unittest tests.test_user
 - python -m unittest tests.test_autho
