language: python
python:
 - "2.7"
#command to install deps:
install: "pip install -r testing_requirements.txt"
#command to run tests:
script: 
 - find . -name "*.py" -exec pep8 {} \;
 - nosetests --with-coverage --cover-package=myapp,user,facade,autho 
