language: python
python:
 - "2.7"
#command to install deps:
install: "pip install -r requirements.txt"
#command to run tests:
script: 
 - find . -name "*.py" -exec pep8 {} \;
 - python -m unittest tests.test_user
 - python -m unittest tests.test_autho
 - python -m unittest tests.test_facade
 - python -m unittest tests.views_test
