messaging:
  image: rabbitmq:3
  ports:
   - "5672:5672"
   - "15672:15672"
db:
  image: mongo:latest
  ports:
   - "27017:27017"
autho:
  image: httpprincess/authorizator:latest
  ports:
   - "5000:5000"
updater:
  image: httpprincess/store-updater:latest
  links:
    - db
    - messaging
worker1:
  image: benedicere/metahosting-worker
  links:
    - db
    - messaging
  environment:
    - DB_LOCAL_COLLECTION=dummy1-local-instances
    - WORKER_NAME=dummy1
    - WORKER_DESCRIPTION=dummyworker 1
worker2:
  image: benedicere/metahosting-worker
  links:
    - db
    - messaging
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - DB_LOCAL_COLLECTION=exist-local-instances
    - WORKER_NAME=exist
    - WORKER_DESCRIPTION=exist xml database
    - DOCKER_SOCKET=unix:///var/run/docker.sock
    - WORKER_IMAGE=dariah/exist:latest
    - WORKER_TYPE=workers.docker_worker.DockerWorker
    - WORKER_PUBIP=192.168.99.100
    - WORKER_PUBPORTS=7000:7009
    - INSTANCE_ENDPOINTS=http://127.0.0.1/exist
    - INSTANCE_ENVIRONMENT__EXIST_MEMORY=512
    - INSTANCE_ENVIRONMENT__EXIST_ADMIN_PASSWORD=
facade:
   build: .
   command: /app/run.py
   ports:
    - "8080:8080"
   links:
    - db
    - autho
    - messaging
